name: Build Main

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '12 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      tag: "${{ github.ref_name }}-${{ github.sha }}"
      alias: "latest"
      frontend-version: main
      backend-version: main
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      quay-username: ${{ secrets.QUAY_USERNAME }}
      quay-password: ${{ secrets.QUAY_PASSWORD }}
