name: Build Main

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '12 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true


env:
  KAOTO_TAG: ${{ github.ref_name }}-${{ github.sha }}
  UI_TAG: main
  API_TAG: main
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -DskipTests=true -e

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
        - native
        - jvm
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        check-latest: true
    - name: 'Checkout'
      uses: actions/checkout@v3     
      with:
        repository: KaotoIO/kaoto-backend
        ref: ${{ env.API_TAG }}
    - name: 'Build Container Image (${{ matrix.variant }})'
      run: |
        ./mvnw ${MAVEN_ARGS} clean install \
          -Dpmd.skip=true \
          -DskipTests \
          -P${{ matrix.variant }} \
          -Pcontainer-image \
          -Pstandalone \
          -Dkaoto.ui.branch=${UI_TAG} \
          -Dquarkus.container-image.tag=${KAOTO_TAG}-${{ matrix.variant }} \
          -Dquarkus.container-image.additional-tags=latest-${{ matrix.variant }}
    - name: Run built image
      run: |
        docker images
        docker run -d --rm -p 8081:8081 --name kaoto-standalone kaotoio/standalone:${KAOTO_TAG}-${{ matrix.variant }}
    - name: List running images
      run: |
        docker ps -a
    - name: Check the deployed service URL
      run: |
        curl --fail -sv --retry 15 --retry-delay 1 --retry-all-errors http://localhost:8081/q/health

    #
    # DockerHub
    #

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'Push Images to DockerHub'
      run: |
        docker push docker.io/kaotoio/standalone --all-tags

    #
    # Quay
    #
    - name: Login to Quay.io
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Tag Quay images
      run: |
        docker tag kaotoio/standalone:${KAOTO_TAG}-${{ matrix.variant }} quay.io/kaotoio/standalone:${KAOTO_TAG}-${{ matrix.variant }}
        docker tag kaotoio/standalone:${KAOTO_TAG}-${{ matrix.variant }} quay.io/kaotoio/standalone:latest-${{ matrix.variant }}

    - name: 'Push Images to Quay.io'
      run: |    
        docker push quay.io/kaotoio/standalone --all-tags
