name: Create Release

on:
  workflow_dispatch:
    inputs:
      backend-version:
        required: true
        type: string
      frontend-version:
        required: true
        type: string
      standalone-version:
        required: true
        type: string


env:
  KAOTO_TAG: ${{ inputs.standalone-version }}
  UI_TAG: ${{ inputs.frontend-version }}
  API_TAG:  ${{ inputs.backend-version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Build Container Image (native)'
      run: |
        docker build \
          -f Dockerfile.native \
          --build-arg ui_tag=$UI_TAG \
          --build-arg api_tag=$API_TAG \
          -t docker.io/kaotoio/standalone:${KAOTO_TAG} \
          -t docker.io/kaotoio/standalone:${KAOTO_TAG}-native \
          -t quay.io/kaotoio/standalone:${KAOTO_TAG}-native \
          .
    - name: 'Build Container Image (JVM)'
      run: |
        docker build \
          -f Dockerfile.jvm \
          --build-arg ui_tag=$UI_TAG \
          --build-arg api_tag=$API_TAG \
          -t docker.io/kaotoio/standalone:${KAOTO_TAG}-jvm \
          -t quay.io/kaotoio/standalone:${KAOTO_TAG}-jvm \

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 'Push Images to DockerHub'
      run: |
        docker push docker.io/kaotoio/standalone:${KAOTO_TAG}  
        docker push docker.io/kaotoio/standalone:${KAOTO_TAG}-jvm
        docker push docker.io/kaotoio/standalone:${KAOTO_TAG}-native      

    - name: Login to Quay.io
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: 'Push Images to Quay.io'
      run: |    
        docker push quay.io/kaotoio/standalone:${KAOTO_TAG}
        docker push quay.io/kaotoio/standalone:${KAOTO_TAG}-jvm
        docker push quay.io/kaotoio/standalone:${KAOTO_TAG}-native  