name: Create Release

on:
  workflow_dispatch:
    inputs:
      backend-version:
        required: true
        type: string
      frontend-version:
        required: true
        type: string
      standalone-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: kaotoio/standalone
        tags: |
          type=schedule
          type=semver,pattern={{version}},value=${{ inputs.standalone-version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.standalone-version }}
          type=semver,pattern={{major}},value=${{ inputs.standalone-version }}
          type=sha
    - name: Build to test
      uses: docker/build-push-action@v4
      with:
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:  |
                  UI_TAG=${{ inputs.frontend-version }}
                  API_TAG=${{ inputs.backend-version }}
    - name: Run built image
      run: docker run -d --rm --name kaoto-standalone kaotoio/standalone:${{ steps.meta.outputs.version }}
    - name: Check health
      uses: stringbean/docker-healthcheck-action@v2
      with:
        container: kaoto-standalone
        wait-time: 50
        require-status: running
        require-healthy: true
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Push to Docker.io
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:  |
                  UI_TAG=${{ inputs.frontend-version }}
                  API_TAG=${{ inputs.backend-version }}
    - name: Push to Quay.io
      run: |
            IMG_NAME=quay.io/kaotoio/standalone 
            IMG_VERSION=${{ steps.meta.outputs.version }}
            UI_TAG=${{ inputs.frontend-version }}
            API_TAG=${{ inputs.backend-version }}
            make build-and-push 
