name: Docker Image CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron:  '12 0 * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      if: ${{env.DOCKER_USERNAME != ''}}
      uses: docker/login-action@v1
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kaotoio/standalone
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Build and push
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    - uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
