name: Docker Image CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron:  '12 0 * * *'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kaotoio/standalone
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Get build-args for Docker
      id: build-args
      run: |
        echo "::set-output name=KAOTO_TAG::${{ github.ref_name }}"
        echo "Tag is ${{ github.ref_name }}."
    - name: Build to test
      uses: docker/build-push-action@v3
      with:
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args:  |
                  UI_TAG=${{ steps.build-args.outputs.KAOTO_TAG }}
                  API_TAG=${{ steps.build-args.outputs.KAOTO_TAG }}
    - name: Run built image
      run: docker run -d --rm --name kaoto-standalone kaotoio/standalone:${{ steps.meta.outputs.version }}
    - name: Check health
      uses: stringbean/docker-healthcheck-action@v1
      with:
        container: kaoto-standalone
        wait-time: 50
        require-status: running
        require-healthy: true
    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Quay.io
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Push to Docker.io
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Push to Quay.io
      run: |
            IMG_NAME=quay.io/kaotoio/standalone 
            IMG_VERSION=${{ steps.meta.outputs.version }}
            UI_TAG=${{ steps.build-args.outputs.KAOTO_TAG }}
            API_TAG=${{ steps.build-args.outputs.KAOTO_TAG }}
            make build-and-push 
